# Generated by Django 5.1.4 on 2025-01-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='ST',
        ),
        migrations.AddField(
            model_name='parameters',
            name='C',
            field=models.FloatField(default=1, help_text='Expected total return'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='G0',
            field=models.FloatField(default=0, help_text='Expected total return'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='I0',
            field=models.FloatField(default=0, help_text='Expected total return'),
        ),
    ]
