# Generated by Django 5.1.4 on 2025-01-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation01', '0002_remove_parameters_st_parameters_c_parameters_g0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='C',
            field=models.FloatField(default=1, help_text='The price of a call option calculated using the Black-Scholes model.'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='G0',
            field=models.FloatField(default=0, help_text='Price of G product'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='I0',
            field=models.FloatField(default=0, help_text='Price of I product'),
        ),
    ]
