# Generated by Django 5.1.4 on 2025-01-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation01', '0003_alter_parameters_c_alter_parameters_g0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='C',
            field=models.FloatField(default=1, help_text='The price of call option'),
        ),
    ]
