# Generated by Django 5.1.4 on 2025-01-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation01', '0004_alter_parameters_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='Family_Office_Cap_gains_tax',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='Family_Office_Income_tax',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='Super_Fund_Cap_gains_tax',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='Super_Fund_Income_tax',
        ),
        migrations.AddField(
            model_name='parameters',
            name='Growth_Party_Cap_gains_tax',
            field=models.FloatField(default=0.235, help_text='Capital gains tax rate for Growth Party'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='Growth_Party_Income_tax',
            field=models.FloatField(default=0.3, help_text='Income tax rate for Growth Party'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='Income_Party_Cap_gains_tax',
            field=models.FloatField(default=0.235, help_text='Capital gains tax rate for Income Party'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='Income_Party_Income_tax',
            field=models.FloatField(default=0.3, help_text='Income tax rate for Income Party'),
        ),
    ]
