# Generated by Django 5.1.4 on 2025-01-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation01', '0005_remove_parameters_family_office_cap_gains_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='tax',
            field=models.JSONField(default={'a': 1}),
            preserve_default=False,
        ),
    ]
