# Generated by Django 5.1.4 on 2025-01-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation01', '0006_simulationresult_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='tax_static',
            field=models.JSONField(default={'a': 1}),
            preserve_default=False,
        ),
    ]
