# Generated by Django 5.1.4 on 2025-01-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation01', '0007_simulationresult_tax_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='static',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='tax',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='tax_static',
            field=models.JSONField(default={}),
        ),
    ]
